site_name: LightFi
site_description: LightFi sensor and data documentation
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    # Need to sponsor mkdocs material to get this via "Insiders"
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
          # features:
  # - search.suggest
  # - search.highlight
  # - content.tabs.link
  # icon:
  #   repo: fontawesome/brands/github-alt
  logo: img/logo_512x512_white.png
  #favicon: img/favicon.png
markdown_extensions:
  # Code highlighting https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html  # Allows figure captions
  # - attr_list  # Allow image resize
